
/**
 * run.pay — Services Bundle
 * 4 vrais services fonctionnels :
 * 1. Web Scraper Pro
 * 2. PDF Generator
 * 3. Phone Validator
 * 4. Screenshot API
 */
 
import express from 'express';
 
const app = express();
app.use(express.json());
 
const RUNPAY_KEY = process.env.RUNPAY_KEY;
const PUBLIC_URL = process.env.PUBLIC_URL;
const API_BASE = 'https://runpay-backend-visibility-production.up.railway.app';
 
// ─── SECURITY ─────────────────────────────────────────────────────────────────
function verifyRunPay(req, res, next) {
  const callId = req.headers['x-runpay-call-id'];
  if (!callId) return res.status(403).json({ error: 'Unauthorized — only callable via run.pay' });
  next();
}
 
// ─── HEALTHCHECK ──────────────────────────────────────────────────────────────
app.get('/', (req, res) => {
  res.json({
    name: 'run.pay Services Bundle',
    version: '1.0.0',
    services: ['web-scraper', 'pdf-generator', 'phone-validator', 'screenshot'],
    status: 'ok'
  });
});
 
// ─── 1. WEB SCRAPER ───────────────────────────────────────────────────────────
app.post('/scrape', verifyRunPay, async (req, res) => {
  const { url } = req.body;
  if (!url) return res.status(400).json({ error: 'url required' });
 
  try {
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
      },
      signal: AbortSignal.timeout(15000)
    });
 
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const html = await response.text();
 
    const title = html.match(/<title[^>]*>(.*?)<\/title>/i)?.[1]?.trim() || '';
    const description = html.match(/<meta[^>]*name=["']description["'][^>]*content=["'](.*?)["']/i)?.[1] || '';
    const content = html
      .replace(/<script[\s\S]*?<\/script>/gi, '')
      .replace(/<style[\s\S]*?<\/style>/gi, '')
      .replace(/<!--[\s\S]*?-->/g, '')
      .replace(/<[^>]+>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .substring(0, 8000);
 
    const links = [...html.matchAll(/href=["'](https?:\/\/[^"']+)["']/gi)]
      .map(m => m[1]).filter((v, i, a) => a.indexOf(v) === i).slice(0, 20);
 
    const images = [...html.matchAll(/src=["'](https?:\/\/[^"']+\.(?:jpg|jpeg|png|gif|webp))["']/gi)]
      .map(m => m[1]).slice(0, 10);
 
    res.json({ success: true, url, title, description, content, links, images, scraped_at: new Date().toISOString() });
  } catch (err) {
    res.status(500).json({ error: err.message, url });
  }
});
 
// ─── 2. PDF GENERATOR ─────────────────────────────────────────────────────────
app.post('/pdf', verifyRunPay, (req, res) => {
  const { title, content, type = 'document', data } = req.body;
  if (!title && !content && !data) return res.status(400).json({ error: 'title or content required' });
 
  const styles = `
    body{font-family:Arial,sans-serif;margin:40px;color:#333;line-height:1.6}
    h1{color:#1a1a2e;border-bottom:2px solid #00e87a;padding-bottom:10px}
    h2{color:#16213e;margin-top:24px}
    table{width:100%;border-collapse:collapse;margin-top:16px}
    th{background:#f5f5f5;padding:10px;text-align:left;border:1px solid #ddd}
    td{padding:10px;border:1px solid #ddd}
    .footer{margin-top:40px;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:10px}
    .badge{background:#00e87a;color:#000;padding:3px 8px;border-radius:3px;font-size:11px}
  `;
 
  let body = '';
  if (type === 'invoice' && data) {
    const items = data.items || [];
    const total = items.reduce((a, i) => a + (i.qty || 1) * (i.price || 0), 0);
    body = `
      <p><strong>Invoice #:</strong> ${data.invoice_number || 'INV-001'}</p>
      <p><strong>Date:</strong> ${data.date || new Date().toLocaleDateString()}</p>
      <p><strong>Client:</strong> ${data.client || ''}</p>
      <table><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr>
      ${items.map(i => `<tr><td>${i.description}</td><td>${i.qty||1}</td><td>${i.price||0}€</td><td>${(i.qty||1)*(i.price||0)}€</td></tr>`).join('')}
      </table><p style="text-align:right;margin-top:12px"><strong>Total: ${total}€</strong></p>
    `;
  } else if (type === 'report' && data?.sections) {
    body = data.sections.map(s => `<h2>${s.title}</h2><p>${s.content}</p>`).join('');
  } else {
    body = `<p>${content || JSON.stringify(data || {}, null, 2)}</p>`;
  }
 
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title||'Document'}</title><style>${styles}</style></head><body><h1>${title||'Document'}</h1>${body}<div class="footer">Generated by <span class="badge">run.pay</span> PDF Generator • ${new Date().toISOString()}</div></body></html>`;
 
  res.json({
    success: true,
    title: title || 'Document',
    html,
    html_base64: Buffer.from(html).toString('base64'),
    size_bytes: Buffer.byteLength(html),
    generated_at: new Date().toISOString()
  });
});
 
// ─── 3. PHONE VALIDATOR ───────────────────────────────────────────────────────
app.post('/phone', verifyRunPay, (req, res) => {
  const { phone } = req.body;
  if (!phone) return res.status(400).json({ error: 'phone required' });
 
  const cleaned = phone.replace(/[\s\-\.\(\)]/g, '');
 
  const prefixes = {
    '+33':{ country:'France', code:'FR' },
    '+1': { country:'USA/Canada', code:'US' },
    '+44':{ country:'United Kingdom', code:'GB' },
    '+49':{ country:'Germany', code:'DE' },
    '+34':{ country:'Spain', code:'ES' },
    '+39':{ country:'Italy', code:'IT' },
    '+32':{ country:'Belgium', code:'BE' },
    '+41':{ country:'Switzerland', code:'CH' },
    '+31':{ country:'Netherlands', code:'NL' },
    '+212':{ country:'Morocco', code:'MA' },
    '+213':{ country:'Algeria', code:'DZ' },
    '+216':{ country:'Tunisia', code:'TN' },
    '+971':{ country:'UAE', code:'AE' },
    '+966':{ country:'Saudi Arabia', code:'SA' },
  };
 
  let detected = null, prefix = null;
  for (const [p, info] of Object.entries(prefixes)) {
    if (cleaned.startsWith(p)) { detected = info; prefix = p; break; }
  }
 
  let lineType = 'unknown';
  if (detected?.code === 'FR') {
    const local = cleaned.replace('+33', '0');
    if (local.startsWith('06') || local.startsWith('07')) lineType = 'mobile';
    else if (/^0[1-5]/.test(local)) lineType = 'landline';
    else if (local.startsWith('08')) lineType = 'special';
  }
 
  const isValid = cleaned.length >= 8 && cleaned.length <= 15 && /^\+?[0-9]+$/.test(cleaned);
  const e164 = cleaned.startsWith('+') ? cleaned : `+${cleaned}`;
 
  res.json({
    success: true,
    input: phone,
    e164,
    is_valid: isValid,
    country: detected?.country || 'Unknown',
    country_code: detected?.code || 'XX',
    country_prefix: prefix || 'unknown',
    line_type: lineType,
    digits: cleaned.replace('+', '').length,
    validated_at: new Date().toISOString()
  });
});
 
// ─── 4. SCREENSHOT API ────────────────────────────────────────────────────────
app.post('/screenshot', verifyRunPay, async (req, res) => {
  const { url, width = 1280, height = 800 } = req.body;
  if (!url) return res.status(400).json({ error: 'url required' });
 
  try {
    // Utilise l'API thum.io gratuite pour les screenshots
    const screenshotUrl = `https://image.thum.io/get/width/${width}/crop/${height}/${url}`;
    const ogImageUrl = `https://image.thum.io/get/og/${url}`;
 
    res.json({
      success: true,
      url,
      screenshot_url: screenshotUrl,
      og_image_url: ogImageUrl,
      viewport: { width, height },
      format: 'PNG',
      taken_at: new Date().toISOString()
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
 
// ─── AUTO-PUBLISH SUR RUN.PAY ─────────────────────────────────────────────────
async function publishServices() {
  if (!RUNPAY_KEY || !PUBLIC_URL) {
    console.log('⚠️  RUNPAY_KEY ou PUBLIC_URL manquant — services non publiés automatiquement');
    console.log('   Ajoute ces variables dans Railway et redéploie.');
    return;
  }
 
  const services = [
    {
      name: 'Web Scraper Pro',
      description: 'Extract text, title, links and images from any public URL. Returns clean structured JSON.',
      endpoint_url: `${PUBLIC_URL}/scrape`,
      price_per_call: 0.005,
      category: 'DATA'
    },
    {
      name: 'PDF Generator',
      description: 'Generate professional PDFs from JSON. Supports invoices, reports and custom documents. Returns HTML renderable as PDF.',
      endpoint_url: `${PUBLIC_URL}/pdf`,
      price_per_call: 0.008,
      category: 'AI'
    },
    {
      name: 'Phone Validator',
      description: 'Validate phone numbers worldwide. Returns country, line type (mobile/landline) and E164 format.',
      endpoint_url: `${PUBLIC_URL}/phone`,
      price_per_call: 0.002,
      category: 'DATA'
    },
    {
      name: 'Screenshot API',
      description: 'Capture any website as PNG. Custom viewport dimensions supported. Instant results.',
      endpoint_url: `${PUBLIC_URL}/screenshot`,
      price_per_call: 0.015,
      category: 'MEDIA'
    }
  ];
 
  console.log('📡 Publication des services sur run.pay...');
  for (const service of services) {
    try {
      const res = await fetch(`${API_BASE}/api/services`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Api-Key': RUNPAY_KEY },
        body: JSON.stringify(service)
      });
      const data = await res.json();
      if (data.service_id) console.log(`✅ ${service.name} publié`);
      else console.log(`⚠️  ${service.name}: ${data.error}`);
    } catch (err) {
      console.error(`❌ ${service.name}:`, err.message);
    }
  }
}
 
// ─── START ────────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3000;
app.listen(PORT, '0.0.0.0', () => {
  console.log('run.pay Services Bundle v1.0 — Port ' + PORT + ' — Ready');
  console.log('Routes: /scrape /pdf /phone /screenshot');
});
